### ISSUE TITLE
GUI doesn't work for some reason

### ISSUE THREAD

**Issue by sidoka-contact** [Kataiser/tf2-rich-presence#303]
Did a fresh install of the app and can't open the gui. The actual rich presence works fine, but I can't un-minimize the app (probably because there's no gui actually open?)
I use the .bat file included with the install to open the app
![изображение](https://user-images.githubusercontent.com/85040993/231752053-8e756405-9212-4a4b-bef0-dc9c26b58358.png)
Basically, when I click on this black rectangle, nothing opens

**Comment by Kataiser** [comment]
Huh strange, I don't see how the main program could be working but the GUI wouldn't be since it's all single threaded. Could you send me your post recent log in `C:\Users\USERNAME\AppData\Roaming\TF2 Rich Presence\logs`? And also try launching from the start menu shortcut, which shouldn't make a difference but still.

**Comment by SowbugMori** [comment]
Check the DB.json file (C:\Users\USERNAME\AppData\Roaming\TF2 Rich Presence\db.json)

I was running into this issue and turns out that the value saved for the GUI position was incorrect. This was mine for example.
`"gui_position": [
        -31750,
        -31875
    ]`

Setting it to this value instead will center it on the screen. Afterward, I turned off the "Remember previous window position" setting. 

`"gui_position": [
        0,
        0
    ]`

That should fix it!

**Comment by Kataiser** [comment]
Oh it totally does for some reason, thanks Windows? I'll add a safety check to fix it, thanks for the report.
