### ISSUE TITLE
Application won't open although it is running on the taskbar

### ISSUE THREAD

**Issue by KeoLightz** [Kataiser/tf2-rich-presence#311]
The application is running on my computer like usual, but when you click on the app the window isn't being brought up. Is it an issue of some sort? I am trying to change some settings but it won't even let me. It's stuck on a black screen
![image](https://github.com/Kataiser/tf2-rich-presence/assets/49461218/24e9a746-9082-46b8-9b14-6e7fd5acad88)

**Comment by Kataiser** [comment]
Yeah this was just reported the other day, I know the issue but still need to get around to fixing it. It's caused by closing the program while it's minimized, which for some reason saves the last window position as very off screen. You can fix it by opening `%AppData%\TF2 Rich Presence\DB.json` and setting gui_position to 0, 0

**Comment by KeoLightz** [comment]
Thank you very much!
