### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by Jan200101** [Kataiser/tf2-rich-presence#54]
At the moment the 7zip executable is being bundled in this repository, which is licensed under GNU LGPL
because of that tf2-rich-presence must be under LGPL 2.1 or later

**Comment by Kataiser** [comment]
Ah, you're probably right. I'll give it a look at some point.

**Comment by Kataiser** [comment]
According to https://choosealicense.com/licenses/lgpl-3.0, "a larger work using the licensed work through interfaces provided by the licensed work may be distributed under different terms and without source code for the larger work." Seems like I can redistribute the binaries as long as the license is there. IDK maybe that's not true, licenses are confusing

**Comment by Jan200101** [comment]
It doesn't matter which you choose but it must be LGPL 2.1 or later as read in the 7zip license under build_tools

**Comment by Kataiser** [comment]
I really wanted to get this right, so I did some more research. Turns out that keeping the same license only applies when modifying the LGPL program (7zip)'s source. Because I'm only redistributing the binaries and including 7zip's license file, and there is a clear separation between components (7zip vs TF2 Rich Presence), I can use any license I want. 

> [The main difference between the GPL and the LGPL is that the latter allows the work to be linked with (in the case of a library, "used by") a non-(L)GPLed program, regardless of whether it is free software or proprietary software.[2] The non-(L)GPLed program can then be distributed under any terms if it is not a derivative work.](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License)

If I'm *still* wrong, that's alright, just reopen this issue and I'll fix it.
